spring.application.name=category-service
server.port=9091

#to tell which type of config then need to get from config server
#if not tell then it will take common configuration
#Spring Boot reads the profiles before loading config server
spring.profiles.active=dev

#config client configurations to getting common config for cat service
spring.config.import=optional:configserver:http://localhost:9094

#Rabbit mq configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

